name = "dev-unigro"
compatibility_date = "2026-03-04"
main = "src/worker.ts"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[env.prod]
name = "unigro"
routes = [
  { pattern = "unigro.abdullahnettoor.com", custom_domain = true }
]

